scrape_configs:
  - job_name: catalog
    scrape_interval: 10s
    static_configs:
      - targets: ["host.docker.internal:4444"]
  - job_name: identity
    scrape_interval: 10s
    static_configs:
      - targets: ["host.docker.internal:4445"]
  - job_name: inventory
    scrape_interval: 10s
    static_configs:
      - targets: ["host.docker.internal:4446"]
